services:
  react-app:
    build: ./frontend    # Caminho corrigido para a pasta da imagem
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  # Quando estiver pronto para o Python, basta descomentar:
  # api-python:
  #   build: ./backend
  #   ports:
  #     - "8000:8000"